# Generated by Django 3.2 on 2025-05-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0003_auto_20250422_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'address'},
        ),
    ]
